[package]
name = "bevygame"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17", features = ["dynamic_linking", "jpeg"] }
bevy-inspector-egui = "0.35.0"
bevy_egui = "0.38.1"
bevy_rapier3d = { version = "0.32.0", features = [ "simd-stable", "debug-render-3d" ] }

